### PR TITLE
Admin lte

### PR DESCRIPTION
**Pull request by fego-dev**
# Description
This change is for add Admin Lte template on the project.
 
  
  ## Screenshots 
imagen

### CODE REVIEW

**Review by MiguelOcegueraM — APPROVED** [review]
looks good! goo job mates

**Review by LPMendoza — APPROVED** [review]
The interface looks very good. God job!

**Comment by Solenasth** [comment]
I cannot approve this pull request because it's imposible for me to review it. 
this PR affects _175 files and 55,000+ lines of code_, there Is no realistic way _any engineer_ can reliable review that. this violates the single responsibility principle for PR's and opens the doors to introduce a lot of bugs. 

 For big features like this it's better to create a feature branch: 
Example `feature/admin_screen` then create branches from there for individual and most importantly: _small features_ that can be reviewed independently. 
Then point those PR's to the feature branch, and merge independently. 
for example
`feature/admin_screen/baseUi` with a pr that points to `feature/admin_screen` 
`feature/admin_screen/support_for_x_feature` with a pr that points to `feature/admin_screen` 
And so on. 

as a general rule of thumb, more than 400 lines of code of changes is _Too big to humanly and reliably review_, instead try to keep it in about 10 files max and less than 500 lines of code. 

IF your feature is bigger, then it most likely needs to be split again. 

For more information check the following articles:
 
[The anatomy of a perfect PR](https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067 )
[The art of making small pull requests ](https://essenceofcode.com/2019/10/29/the-art-of-small-pull-requests/)
[How to avoid making giant pull requests](https://revelry.co/resources/development/pull-requests-code-review/)

**Review by LDVera — APPROVED** [review]

**Comment by fego-dev** [comment]
Add Admin LTE  GEM

**Pull request merged**
